###################################################
#              变量配置文件  ---  测试环境         #
###################################################
server:
  port: 8957
  servlet:
    context-path: /basic-backend
spring:
  #  数据库配置
  datasource:
    dynamic:
      primary: basic
      datasource:
        basic: # 基础数据源
          type: com.alibaba.druid.pool.DruidDataSource
          username: picture_basic_backend
          password: BMHcmWy43DMmRxNG
          url: jdbc:mysql://49.232.128.203:3306/picture_basic_backend?rewriteBatchedStatements=true
          driver-class-name: com.mysql.cj.jdbc.Driver
      strict: false
    druid:
      initial-size: 5 # 连接池初始化时创建的连接数。默认值为0。
      min-idle: 5 # 连接池中保持的最小空闲连接数量。当连接池中的连接数量小于这个值时，连接池会尝试创建新的连接。默认值为0。
      max-active: 20 # 连接池中允许的最大连接数。如果所有连接都被使用并且没有空闲连接，新的连接请求将被阻塞，直到有连接可用。默认值为8。
      max-wait: 60000 # 获取连接时的最大等待时间，单位为毫秒。如果在指定的时间内无法获取到连接，将抛出异常。默认值为-1，表示无限等待。
      time-between-eviction-runs-millis: 60000 # 连接池每次检测空闲连接的间隔时间，单位为毫秒。默认值为60000毫秒（1分钟）。
      min-evictable-idle-time-millis: 300000 # 连接在连接池中的最小空闲时间，超过这个时间的连接将被回收，单位为毫秒。默认值为300000毫秒（5分钟）。
      validation-query: SELECT 1 # 用于验证连接是否有效的SQL查询语句。Druid会定期执行此查询来检测连接的可用性。默认为"SELECT 1"。
      test-while-idle: true # 是否在连接空闲时检测连接的有效性。如果设置为true，则连接池会定期检测空闲连接，如果连接失效，将被标记为不可用并移除。默认为true。
      test-on-borrow: false # 是否在从连接池借用连接时检测连接的有效性。如果设置为true，每次从连接池借用连接时都会执行连接有效性检测。默认为false。
      test-on-return: false # 是否在归还连接到连接池时检测连接的有效性。如果设置为true，连接在归还到连接池时会进行有效性检测。默认为false。
      pool-prepared-statements: true # 是否开启预处理语句池。预处理语句池可以提高性能，特别是在执行相同SQL语句多次时。默认为true。
      max-pool-prepared-statement-per-connection-size: 20 #每个连接上允许的最大预处理语句数。默认值为20。
# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 下划线自动转换为驼峰
    map-underscore-to-camel-case: true
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 云图库接口文档
    description: 云图库接口文档
    version: 1.0.0
    group:
      user:
        group-name: userModule
        api-rule: package
        api-rule-resources:
          - com.manneia.manneiapicturebackend.controller
#    日志配置
logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG