###################################################
#              变量配置文件  ---  生产环境         #
###################################################
server:
  port: 8957
  servlet:
    context-path: /zyhb
